version: '3.3'
services:
  alist:
    image: 'openlistteam/openlist:latest'
    container_name: alist
    volumes:
      - '/root/alist:/opt/alist/data'
    ports:
      - '${webport}:5244'
      - 8003:8003
    user: '0:0'
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
