networks:
  net-bridge:
    external: true

services:
  alist2strm:
    image: mccray/alist2strm:latest
    container_name: alist2strm
    restart: unless-stopped
    networks:
      - net-bridge
    ports:
      - "${web}:80"   # 前端访问端口
      - "${api}:3210" # 后端API端口
    volumes:
      # 数据挂载目录
      - /root/alist2strm/data:/app/data
      # 媒体目录
      - /root/alist2strm/strm:/strm
    environment:
      - 'PUID=1000'
      - 'PGID=0'
      - 'UMASK=000'
      - 'TZ=Asia/Shanghai'
      # 用户相关
      - 'JWT_SECRET={guo1015666...}'
      - 'USER_NAME={admin}'
      - 'USER_PASSWORD={guo1015666...}'
