version: "3"
services:
  ani-rss:
    container_name: ani-rss
    volumes:
      - /root/ani-rss/config:/config
      - /root/downloads:/downloads
    ports:
      - ${webport}:7789
    environment:
      - PORT=7789
      - CONFIG=/config
      - TZ=Asia/Shanghai
      - PUID=0
      - PGID=0
      - UMASK=022
    image: wushuo894/ani-rss:latest
    logging:
      driver: json-file
      options:
        max-size: 30m
        max-file: 2
    restart: always
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
