version: "3.8"
services:
  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - RPC_SECRET=taikong
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=true
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
      - SPECIAL_MODE=move
    volumes:
      - /root/aria/aria2-config:/config
      - /root/aria/aria2-downloads:/downloads
      - /root/aria/aria2-completed:/completed
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
    networks:
      - net-bridge
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port ${webport}
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: json-file
      options:
        max-size: 1m
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
