version: "3.8"
services:
  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - RPC_SECRET=guo1015666...
      - DISK_CACHE=128M
      - IPV6_MODE=true
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
      - SPECIAL_MODE=move
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 2
    volumes:
      - /root/aria/aria2-config:/config
      - /root/aria/aria2-downloads:/downloads
      - /root/downloads/speed:/completed
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped
    networks:
      - net-bridge
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    restart: unless-stopped
    ports:
      - ${webport}:6880
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 2
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
