version: '3.9'
services:
  autofilm:
    image: akimio/autofilm
    volumes:
      - '/root/autofilm/logs:/logs'
      - '/root/autofilm/media:/media'
      - '/root/autofilm/config:/config'
    environment:
      - TZ=Asia/Shanghai
    container_name: autofilm
    networks:
      - net-bridge
    logging:
      driver: loki
      options:
        loki-url: "http://152.53.134.9:3100/loki/api/v1/push"
        max-size: "50m"
        max-file: "15"
        loki-batch-size: "400"
networks:
  net-bridge:
    external: true
