version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: danmu-postgres
	restart: unless-stopped
    ports:
      - ${pgport}:5432
    environment:
      # !!! 重要：请务必替换为您的强密码 !!!
      POSTGRES_PASSWORD: "${password}"               #数据库密码
      POSTGRES_USER: "danmuapi"                                        #数据库用户名
      POSTGRES_DB: "danmuapi"                                          #数据库名称
      TZ: "Asia/Shanghai"
    volumes:
      - /root/danmu-server/db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U danmuapi -d danmuapi"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    networks:
      - net-bridge

  danmu-app:
    image: l429609201/misaka_danmu_server:latest
    container_name: danmu-server
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # 设置运行容器的用户和组ID，以匹配您宿主机的用户，避免挂载卷的权限问题。
      - PUID=0
      - PGID=0
      - UMASK=000
      # --- 数据库连接配置 ---
      - DANMUAPI_DATABASE__TYPE=postgresql                              # 数据库类型
      - DANMUAPI_DATABASE__HOST=postgres                                # 使用服务名
      - DANMUAPI_DATABASE__PORT=54325                                    # 数据库端口
      - DANMUAPI_DATABASE__NAME=danmuapi                                # 数据库名称
      # !!! 重要：请使用上面postgres容器相同的用户名和密码 !!!
      - DANMUAPI_DATABASE__USER=danmuapi                                # 数据库用户名    
      - DANMUAPI_DATABASE__PASSWORD=${password}      # 数据库密码
      # --- 初始管理员配置 ---
      - DANMUAPI_ADMIN__INITIAL_USER=admin
    volumes:
      - /root/danmu-server/config:/app/config
    ports:
      - "${webport}:7768"

    networks:
      - net-bridge

networks:
  net-bridge:
    driver: bridge
