version: '3.8'
services:
  app:
    # 替换为您自己的Docker Hub用户名和镜像名，或使用本地构建
    image: l429609201/misaka_danmu_server:latest
    container_name: danmu-server
    restart: unless-stopped
    networks:
      - net-bridge
    ports:
      - ${webport}:7768
    environment:
      # --- 用户与组ID (用于运行时，与构建时匹配) ---
      - PUID=0
      - PGID=0
      # --- 数据库连接配置 ---
      - DANMUAPI_DATABASE__HOST=mysql
      - DANMUAPI_DATABASE__PORT=3306
      - DANMUAPI_DATABASE__NAME=danmuapi
      - DANMUAPI_DATABASE__USER=root
      - DANMUAPI_DATABASE__PASSWORD=guo1015666...

      
      # --- 初始管理员配置 ---
      - DANMUAPI_ADMIN__INITIAL_USER=admin
    volumes:
      # 挂载配置文件目录，用于持久化日志等
      - /root/danmu-server/config:/app/config


networks:
  net-bridge:
    external: true
