version: "3"

services:
  web:
    image: stilleshan/dujiaoka
    environment:
        # - INSTALL=false
        - INSTALL=false
        # - MODIFY=true
    volumes:
      - /root/dujiaka/env.conf:/dujiaoka/.env
      - /root/dujiaka/uploads:/dujiaoka/public/uploads
      - /root/dujiaka/storage:/dujiaoka/storage
    ports:
      - ${webport}:80         # 8090可以改成任意服务器没有使用过的端口，80不要修改
    restart: always
    networks:
      - net-bridge
 
  db:
    image: mariadb:focal
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=guo1015666...
      - MYSQL_DATABASE=dujiaoka
      - MYSQL_USER=dujiaoka
      - MYSQL_PASSWORD=guo1015666...
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - net-bridge

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis:/data
    environment:
      - REDIS_PASSWORD=guo1015666...
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
