version: '3.8'
services:
  emby-pulse:
    image: zeyu8023/emby-stats:latest
    container_name: emby-manager
    restart: unless-stopped
    networks:
      - net-bridge
    ports:
      - ${webport1}:10307
      - ${webport2}:10308
    volumes:
      - /root/emby-pulse/config:/app/config
    environment:
      - TZ=Asia/Shanghai
      - EMBY_HOST=https://emby.taikong.de
      - EMBY_API_KEY=bb6bb8a178db4558837f3a02a2d06caf
networks:
  net-bridge:
    external: true
