version: '3.8'

services:
  # --- 1. Emby-Toolkit 主程序 ---
  emby-toolkit:
    image: hbq0405/emby-toolkit:latest 
    container_name: emby-toolkit
    networks:
      - net-bridge
    ports:
      - "${webport}:5257"                               # 管理端口
    volumes:
      - /root/emby-toolkit/config:/config                # 将宿主机的数据目录挂载到容器的 /config 目录
      - /strmstorage:/tmdb                          # 映射神医本地TMDB目录，非神医Pro用户可以留空
      - /var/run/docker.sock:/var/run/docker.sock # 一键更新用，不需要可以不配置
    environment:
      - APP_DATA_DIR=/config                      # 持久化目录
      - TZ=Asia/Shanghai                          # 设置容器时区
      - AUTH_USERNAME=admin                       # 用户名可任意设置，密码在程序首次运行会生成初始密码：password
      - PUID=0                                 # 设置为你的用户ID，建议与宿主机用户ID保持一致
      - PGID=0                                 # 设置为DOCKER组ID (一键更新用，‘grep docker /etc/group’可以查询)
      - UMASK=000                                 # 设置文件权限掩码，建议022
      - DB_HOST=emby-toolkit-db                        # 数据库服务的地址 
      - DB_PORT=5432                              # 数据库服务的端口 
      - DB_USER=embytoolkit                       # !!! (可选) 修改为你自己的数据库用户名
      - DB_PASSWORD=${password}                   # !!! (必填) 请修改为一个强密码 !!!
      - DB_NAME=embytoolkit                       # !!! (可选) 修改为你自己的数据库名
      - CONTAINER_NAME=emby-toolkit               # 以下两项都是一键更新用，不需要可以不配置
      - DOCKER_IMAGE_NAME=hbq0405/emby-toolkit:latest
    restart: unless-stopped
networks:
  net-bridge:
    external: true
