version: '3.9'
services:
  fastemby:
    image: 'shenxianmq/fastemby:latest'
    volumes:
      - '/root/fastemby/log:/app/log'
      - '/root/fastemby/config:/app/config'
    environment:
      - TZ=Asia/Shanghai
    container_name: fastemby
    networks:
      - net-bridge
    restart: always
    ports:
      - ${webport}:15895
      - 3030:3030
      - 8098:8098
networks:
  net-bridge:
    external: true
