version: '3.9'
services:
  fastemby:
    image: 'shenxianmq/fastemby:latest'
    volumes:
      - '/root/fastemby/log:/app/log'
      - '/root/fastemby/config:/app/config'
    environment:
      - TZ=Asia/Shanghai
    container_name: fastemby
    restart: always
    network_mode: host
    logging:
      driver: loki
      options:
        loki-url: "http://152.53.134.9:3100/loki/api/v1/push"
        max-size: "50m"
        max-file: "15"
        loki-batch-size: "400"
