version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    networks:
      - net-bridge
    restart: always
    user: "0:0"
    ports:
      - "${webport}:80"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /:/srv
      - /root/filebrowser/database.db:/etc/database.db
      - /root/filebrowser/config.json:/etc/config.json
networks:
  net-bridge:
    external: true
