version: '3'
services:
  gpt4free:
    image: hlohaus789/g4f:latest
    container_name: "g4f"
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - /root/g4f:/app
    ports:
      - '${webport}:8080'
      - '1337:1337'
      - '7900:7900'
    networks:
      - net-bridge
    environment:
      - TZ=Asia/Shanghai
networks:
  net-bridge:
    external: true
