version: '3.3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - ${grafanawebport}:3000
    networks:
      - net-bridge
    environment:
      - TZ=Asia/Shanghai
    restart: always
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    #privileged: true
    volumes:
      - /root/loki:/etc/loki
    ports:
      - "${lokiport}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net-bridge
    restart: always
  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - /root/nginx-proxy-manager/data/logs:/var/log
      #- /root/promtail/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/config.yml
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net-bridge
    restart: always
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    hostname: node_exporter
    environment:
      - TZ=Asia/Shanghai
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'
  prometheus:
    image: prom/prometheus:v2.26.0
    restart: always
    container_name:  prometheus
    hostname:  prometheus
    networks:
      - net-bridge
    environment:
      - TZ=Asia/Shanghai
    ports:
      - ${prometheusport}:9090
    volumes:
      - /root/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.retention.time=7d'  # 保留7天数据
  cadvisor:
    image: 'gcr.io/cadvisor/cadvisor:latest'
    devices:
      - /dev/kmsg
    privileged: true
    networks:
      - net-bridge
    environment:
      - TZ=Asia/Shanghai
    container_name: cadvisor
    ports:
      - '${cadvisorport}:8080'
    volumes:
      - '/dev/disk/:/dev/disk:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/sys:/sys:ro'
      - '/var/run:/var/run:ro'
      - '/:/rootfs:ro'
    restart: always
networks:
  net-bridge:
    external: true
