version: '3.3'
services:
  it-tools:
    container_name: it-tools
    restart: unless-stopped
    ports:
      - '${webport}:80'
    image: 'qingfeng2336/it-tools:latest'
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
