version: '3.9'
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Asia/Shanghai
      - JELLYFIN_TYPE=emby
    ports:
      - ${webport}:5055
    volumes:
      - /root/jellyseerr/config:/app/config
    restart: unless-stopped
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
