version: '3'
services:
  jellystat-db:
    image: 'postgres:15.2'
    shm_size: 1gb
    container_name: jellystat-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
    volumes:
      - '/root/postgres:/var/lib/postgresql/data'
  jellystat:
    image: 'cyfershepard/jellystat:latest'
    container_name: jellystat
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ${jwt-secret}
      IS_EMBY_API: true
      TZ: Asia/Shanghai
    volumes:
      - '/root/jellystat:/app/backend/backup-data'
    ports:
      - '${webport}:3000'
    depends_on:
      - jellystat-db
networks:
  net-bridge:
    external: true
