services:
  mediawarp:
    image: akimio/mediawarp:0.1.0
    container_name: MediaWarp
    restart: unless-stopped
    ports:
      - ${webport}:9000
    volumes:
      - /root/mediawarp/config:/config
      - /root/mediawarp/logs:/logs
      - /root/mediawarp/static:/static
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
