version: '3.3'
services:
  moviepilot:
    deploy:
      resources:
        limits:
          memory: 4G
    stdin_open: true
    tty: true
    container_name: moviepilotv2
    hostname: moviepilotv2
    ports:
      - '${webport}:3000'
      - '3001:3001'
    volumes:
      - '/root/downloads:/downloads'
      - '/root/moviepilot-v2/config:/config:rw'
      - '/root/moviepilot-v2/core:/moviepilot/.cache/ms-playwright'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/root/cd2/mnt:/CloudNAS:shared'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=000
      - TZ=Asia/Shanghai
      - AUTH_SITE=iyuu
      - IYUU_SIGN=IYUU4338Ta698600be53e28eeb1db11eebc2cfb70fd0446c3
      - SUPERUSER=admin
      - DB_TYPE=postgresql
      - DB_POSTGRESQL_HOST=mp-pgsql
      - DB_POSTGRESQL_PORT=5432
      - DB_POSTGRESQL_DATABASE=moviepilot
      - DB_POSTGRESQL_USERNAME=moviepilot
      - DB_POSTGRESQL_PASSWORD=${pgdb-pass}   # 注意和下面的postgres保持一致
      - CACHE_BACKEND_TYPE=redis
      - CACHE_BACKEND_URL=redis://:${redis-pass}@mp-redis:6379/0 # 注意和下面的redis保持一致
      # - 'API_TOKEN=无需手动配置，系统会自动生成。如果需要自定义配置，必须为16位以上的复杂字符串'
    restart: always
    image: jxxghp/moviepilot-v2:latest
    networks:
      - net-bridge

  mp-redis:
    container_name: mp-redis
    image: redis
    command: redis-server --save 600 1 --requirepass ${redis-pass}
    volumes:
      - /mnt/app/data/mp-redis:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net-bridge

  mp-pgsql:
    container_name: mp-pgsql
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: moviepilot
      POSTGRES_USER: moviepilot
      POSTGRES_PASSWORD: guo1015666...   # 和moviepilot环境变量保持一致
    volumes:
      - /root/moviepilot-v2/mp-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moviepilot -d moviepilot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net-bridge

networks:
  net-bridge:
    external: true
