version: "2.1"

services:
  music-tag:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    networks: 
      - net-bridge
    ports:
      - ${webport}:8002
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/cd2/mnt/123网盘/Emby/music:/app/media
      - /root/musicTagWeb:/app/data
      - /root/downloads:/app/download
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://152.53.134.9:3100/loki/api/v1/push"
        max-size: "50m"
        max-file: "15"
        loki-batch-size: "400"
networks:
  net-bridge:
    external: true
