# docker-compose.mysql.yml
version: '3.5'
services:
  mysql:
    image: mysql:8.1.0-oracle
    restart: always
    privileged: true
    container_name: danmu-mysql
    volumes:
      - /root/mysql/data:/var/lib/mysql
      - /root/mysql/conf:/etc/mysql/conf.d
      - /root/mysql/logs:/logs
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      # !!! 重要：请务必替换为您的强密码 !!!
      MYSQL_ROOT_PASSWORD: "${password}"
      MYSQL_DATABASE: "danmuapi"
      MYSQL_USER: "danmuapi"
      MYSQL_PASSWORD: "${password_user}"
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
    networks:
      - net-bridge

networks:
  net-bridge:
    external: true

