services:
  nexterm:
    ports:
      - "${webport}:6989"
    restart: always
    volumes:
      - /root/nexterm:/app/data
    image: germannewsmaker/nexterm:1.0.5-OPEN-PREVIEW
    container_name: "nexterm"
    environment:
      - TZ=Asia/Shanghai
      - ENCRYPTION_KEY="222569f5e7c3dee1ec0f18c3729aa7bb7feb309bc2fd2f183dbf9da094292c6c"
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
