services:
  nexterm:
    ports:
      - "${webport}:6989"
    restart: always
    volumes:
      - /root/nexterm:/app/data
    image: germannewsmaker/nexterm:1.0.3-OPEN-PREVIEW
    container_name: "nexterm"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
