services:
  app:
    image: 'chishin/nginx-proxy-manager-zh:release'
    restart: unless-stopped
    ports:
      - '80:80'
      - '${webport}:81'
      - '443:443'
    container_name: nginx-proxy-manager
    volumes:
      - /root/nginx-proxy-manager/data:/data
      - /root/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - net-bridge
    environment:
      - TZ=Asia/Shanghai
networks:
  net-bridge:
    external: true
