services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '${webport}:81'
      - '443:443'
    container_name: nginx-proxy-manager
    volumes:
      - /root/nginx-proxy-manager/data:/data
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
