version: "2"
services:
  qbittorrentee:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=1233
    volumes:
      - /root/qbittorrentSpeed/config:/config
      - /root/qbittorrentSpeed/theme:/theme
      - /root/downloads:/downloads
    ports:
      - 41256:41256
      - 41256:41256/udp
      - 1233:1233
    logging:
      driver: json-file
      options:
        max-size: 30m
        max-file: 2
    networks:
      - net-bridge
    restart: unless-stopped
networks:
  net-bridge:
    external: true
