version: "2"
services:
  qbittorrentee:
    image: linuxserver/qbittorrent
    container_name: qbittorrentSpeed
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /root/qbittorrentSpeed/config:/config
      - /root/qbittorrentSpeed/theme:/theme
      - /root/downloads:/downloads
    ports:
      - 41256:41256
      - 41256:41256/udp
      - ${webport}:8080
    networks:
      - net-bridge
    restart: unless-stopped
networks:
  net-bridge:
    external: true
