version: "2"
services:
  qbittorrentee:
    image: superng6/qbittorrentee:4.6.6.10
    container_name: qbittorrentee
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - /root/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - ${webport}:8080
    networks:
      - net-bridge
    restart: unless-stopped
networks:
  net-bridge:
    external: true
