version: "3"
services:
  nginx-rtmp:
    image: alfg/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "${streamport}:1935"
      - "${webport}:8080"
    volumes:
      - /root/rtmp/nginx.conf:/etc/nginx/nginx.conf
      - /root/rtmp/hls:/tmp/hls
    restart: always
    networks:
      - net-bridge
    environment:
      - TZ=Asia/Shanghai
networks:
  net-bridge:
    external: true
