version: '3.8'
services:
  symedia:
    image: shenxianmq/symedia:latest  # 拉取最新镜像
    container_name: symedia           # 容器名称
    restart: always                   # 重启策略
    ports:
      - "${webport}:8095"                   # 映射端口：主机 8095 -> 容器 8095
    volumes:
      - /root/cd2/mnt/123网盘:/123网盘:shared  # cd2映射路径
      #- /root/cd2/mnt:/CloudNAS:shared  # cd2映射路径
      - /root/strm:/strm
      - /r2:/aliststrm:shared # 本地媒体目录
      - /root/symedia/config:/app/config  # sa配置文件夹
      - /var/run/docker.sock:/var/run/docker.sock:ro     # Docker 宿主机通信
    environment:
      TZ: Asia/Shanghai             # 容器时区
      LICENSE_KEY: ${activecode}               # 激活码
      COVER_MAKER: True #本次添加
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
