version: '3.3'
services:
  synctv:
    image: 'synctvorg/synctv:latest'
    container_name: synctv
    restart: unless-stopped
    ports:
      - '${webport}:8080/tcp'
      - '${webport}:8080/udp'
    volumes:
      - /root/synctv:/root/.synctv
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    networks:
      - net-bridge
networks:
  net-bridge:
    external: true
