services:
  synctv:
    image: synctvorg/synctv:${SYNCTV_IMAGE_TAG:-latest}
    container_name: synctv-app
    env_file:
      - path: .env.synctv
        required: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "${webport}:8080"
      - "1935:1935"
      - "3748:3478/udp"
    networks:
      - net-bridge
    volumes:
      - '/root/synctv/data:/data'
    restart: unless-stopped

networks:
  net-bridge:
    external: true
