version: '3.9'
services:
  vertex:
    image: 'lswl/vertex:stable'
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '3000:3000'
    volumes:
      - '/root/vertex:/vertex'
    container_name: vertex
    networks:
      - net-bridge
networks:
  netbridge:
    external: true
