version: '3.9'
services:
  vertex:
    image: 'lswl/vertex:stable'
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '${webport}:3000'
    volumes:
      - '/root/vertex:/vertex'
    container_name: vertex
    networks:
      - net-bridge
    logging:
      driver: loki
      options:
        loki-url: "http://152.53.134.9:3100/loki/api/v1/push"
        max-size: "50m"
        max-file: "15"
        loki-batch-size: "400"
networks:
  net-bridge:
    external: true
