services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    user: 1000:1000
    ports:
      - ${webport}:5690
    volumes:
      - /root/wizarr/database:/data/database
      - /root/wizarr/wizard:/data/wizard_steps
    networks:
      - net-bridge
    environment:
      - TZ=Asia/Shanghai
      - DISABLE_BUILTIN_AUTH=false
    restart: always
networks:
  net-bridge:
    external: true
